# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-16 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180328_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('org', '\u57f9\u8bad\u673a\u6784'), ('person', '\u4e2a\u4eba'), ('college', '\u9ad8\u6821')], default='org', max_length=20, verbose_name='\u8bfe\u7a0b\u673a\u6784'),
        ),
    ]
