# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-17 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180416_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='teacher/%Y%m', verbose_name='\u8bb2\u5e08\u7167\u7247'),
        ),
    ]
