# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-17 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='mobile',
            field=models.CharField(blank='', max_length=11, null=True, verbose_name='\u7535\u8bdd'),
        ),
    ]
