# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-24 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180420_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='send_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u53d1\u9001\u65f6\u95f4'),
        ),
    ]
