# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student_num',
        ),
    ]
