# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-27 15:17
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_video_learn_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u8bfe\u7a0b\u8be6\u60c5'),
        ),
    ]
