# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-26 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180326_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank='', max_length=11, null=True, verbose_name='\u624b\u673a'),
        ),
    ]
