# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-24 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180418_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '\u6ce8\u518c'), ('forget', '\u5fd8\u8bb0\u5bc6\u7801'), ('update', '\u4fee\u6539\u90ae\u7bb1')], max_length=20, verbose_name='\u9a8c\u8bc1\u7c7b\u578b'),
        ),
    ]
