# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-24 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180424_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], max_length=6, verbose_name='\u6027\u522b'),
        ),
    ]
